export const FETCH_TODOS = 'FETCH_TODOS'
export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const EDIT_ID = 'EDIT_ID'
export const SAVE_TASK = 'SAVE_TASK'
export const CHANGE_STATUS = 'CHANGE_STATUS'
